name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: C++ CI / ${{ matrix.os }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: gcc
          - os: windows-2022
            compiler: msvc
          - os: macos-14
            compiler: clang

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y cmake g++ libx11-dev libxrandr-dev libudev-dev libgl1-mesa-dev valgrind
          elif [ "${{ runner.os }}" = "macOS" ]; then
            brew install cmake sfml || true
          fi

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build --config Debug --parallel 2

      - name: Install
        run: cmake --install build --prefix build/install

      - name: Skip launcher.command on macOS
        if: runner.os == 'macOS'
        run: |
          echo "Skipping macOS launcher.command since this is a console project"
          touch launcher.command

      - name: Move artifacts
        run: |
          mkdir -p artifacts
          cp -r build/install/* artifacts/ || true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.compiler }}-build
          path: artifacts/

  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: cppcheck --enable=all --suppress=missingIncludeSystem --quiet . || true

  clang-tidy:
    name: Clang-Tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Clang tools
        run: sudo apt-get update && sudo apt-get install -y clang clang-tidy

      - name: Run clang-tidy
        run: clang-tidy **/*.cpp -- -Iinclude -std=c++17 || true
